version: "3.9"

services:
 
  service1: 
    build: 
      context: ./service1/docker
    volumes:
      - ./service1/src:/src
      - ./service1/docker:/docker
    env_file:
      - ./service1/docker/RUN_SECRETS.env
    entrypoint: ["sh", "docker/entrypoint.sh"]
    networks: 
      - internal

  service2: 
    build: 
      context: ./service2/docker
    volumes:
      - ./service2/src:/src
      - ./service2/docker:/docker
    env_file:
      - ./service2/docker/RUN_SECRETS.env
    entrypoint: ["sh", "docker/entrypoint.sh"]
    networks: 
      - internal

  server:
    build:
      context: ./server/docker
    entrypoint: ["nginx", "-g", "daemon off;"]
    ports: 
      - "80:3000"
      - "443:3000"
    depends_on: 
      - service1
      - service2
    networks: 
      - internal

networks: 
  internal:
    driver: bridge