version: "3.9"

services:
 
  blog: 
    build:
      context: ./blog/docker
    volumes: 
      - ./blog:/blog
    working_dir: "/blog"
    entrypoint: ["sh", "docker/entrypoint.sh"]
    networks: 
      - internal

  server:
    build:
      context: ./server/docker
    entrypoint: ["nginx", "-g", "daemon off; pid /tmp/nginx.pid;"]
    ports: 
      - "80:3000"
      - "443:3000"
    depends_on: 
      - blog
    networks: 
      - internal

networks: 
  internal:
    driver: bridge