version: '3.3'

services:

  django: 
    build: 
      context: ./docker
    volumes:
      - ./src:/src
      - ./docker:/docker
    env_file:
      - ./docker/RUN_SECRETS.env
    entrypoint: ["sh", "docker/entrypoint.sh"]
    ports:
      - "80:3000"
      - "443:3000"
